sudo: required

language: java

services:
  - docker

env:
  global:
  - APP=iou
  - REPO=staticvoiduk/$APP
  - COMMIT=${TRAVIS_COMMIT::8}

before_script:
  - scripts/install-k8s-and-config.sh
  - kubectl --kubeconfig kube/kubeconfig apply -f kube/deployment.yml  #Only required so first deployment to k8s env works

after_success:
  - docker build -t $REPO:$COMMIT .
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then scripts/deploy-docker-image-to-k8s.sh; fi
