sudo: required

language: java

services:
  - docker

env:
  global:
  - APP=iou
  - REPO=staticvoiduk/$APP
  - COMMIT=${TRAVIS_COMMIT::8}

after_success:
  - docker build -t $REPO:$COMMIT . --build-arg JAR_FILE=./build/libs/$REPO-0.0.1-SNAPSHOT.jar
