sudo: required

language: java

services:
  - docker

env:
  global:
  - APP=iou
  - REPO=staticvoiduk/$APP
  - COMMIT=${TRAVIS_COMMIT::8}

before_script:
  - scripts/travis-install-k8s.sh
  - kubectl --kubeconfig kube/kubeconfig apply -f kube/deployment.yml

after_success:
  - docker build -t $REPO:$COMMIT .
  - scripts/travis-deploy-image.sh
