---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: iou
  labels:
    app: iou
spec:
  revisionHistoryLimit: 3
  replicas: 3
  selector:
    matchLabels:
      app: iou
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: iou
    spec:
      containers:
      - name: iou
        image: staticvoiduk/iou:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: iou-svc
  annotations:
      external-dns.alpha.kubernetes.io/hostname: iou.staticvoid.co.uk.
  labels:
    app: iou
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: iou
---

